// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testarboristtreewidget.proxies;

public class PageContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pageContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestArboristTreeWidget.PageContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServiceURL("ServiceURL"),
		DataChangedDate("DataChangedDate");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PageContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PageContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pageContextMendixObject)
	{
		if (pageContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, pageContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.pageContextMendixObject = pageContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PageContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testarboristtreewidget.proxies.PageContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testarboristtreewidget.proxies.PageContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testarboristtreewidget.proxies.PageContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testarboristtreewidget.proxies.PageContext(context, mendixObject);
	}

	public static testarboristtreewidget.proxies.PageContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testarboristtreewidget.proxies.PageContext.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ServiceURL
	 */
	public final java.lang.String getServiceURL()
	{
		return getServiceURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceURL
	 */
	public final java.lang.String getServiceURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceURL.toString());
	}

	/**
	 * Set value of ServiceURL
	 * @param serviceurl
	 */
	public final void setServiceURL(java.lang.String serviceurl)
	{
		setServiceURL(getContext(), serviceurl);
	}

	/**
	 * Set value of ServiceURL
	 * @param context
	 * @param serviceurl
	 */
	public final void setServiceURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serviceurl)
	{
		getMendixObject().setValue(context, MemberNames.ServiceURL.toString(), serviceurl);
	}

	/**
	 * @return value of DataChangedDate
	 */
	public final java.util.Date getDataChangedDate()
	{
		return getDataChangedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DataChangedDate
	 */
	public final java.util.Date getDataChangedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DataChangedDate.toString());
	}

	/**
	 * Set value of DataChangedDate
	 * @param datachangeddate
	 */
	public final void setDataChangedDate(java.util.Date datachangeddate)
	{
		setDataChangedDate(getContext(), datachangeddate);
	}

	/**
	 * Set value of DataChangedDate
	 * @param context
	 * @param datachangeddate
	 */
	public final void setDataChangedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datachangeddate)
	{
		getMendixObject().setValue(context, MemberNames.DataChangedDate.toString(), datachangeddate);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pageContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testarboristtreewidget.proxies.PageContext that = (testarboristtreewidget.proxies.PageContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
